//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Project Reality")]
[assembly: System.Reflection.AssemblyProduct("Project Reality")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Project Reality 2013-2014")]
[assembly: System.Reflection.AssemblyVersion("1.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.98.1187")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.1.98.1187")]


